name: ${project.artifactId}
version: ${project.version}
main: com.xice.systemMessage.XiceSystemMessage
api-version: ${apiVersion}
depend:
  - XiceMCLib
permissions:
  xice.systemMessage.reload:
    description: 重载 systemMesssage 配置文件
    default: op
folia-supported: true
author: ${author}
description: ${description}